version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file:
      - .env
    expose:
      - '3000'
      - '9229'
    ports:
      - '3000:3000'
      - "9229:9229"
    command: npm run dev
    depends_on:
      - mysql

  mysql:
    image: woahbase/alpine-mysql:x86_64
    container_name: docker_mysql
    hostname: mysql
    env_file:
      - .env
    environment:
      - PGID=100
      - PUID=1000
      - MYSQL_ROOT_PASSWORD=teddy
      - MYSQL_USER=teddy
      - MYSQL_USER_PWD=teddy
      - MYSQL_USER_DB=teddy
    ports:
      - "3326:3306"
    volumes:
      - db:/var/lib/mysql
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["sh", "-c", "tail -f /dev/null"]

volumes:
  db:
